// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TarlaOtomasyonProjesi2.DAL;

#nullable disable

namespace TarlaOtomasyonProjesi2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220902160056_TarlaPropEkleme")]
    partial class TarlaPropEkleme
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("TarlaOtomasyonProjesi2.Entities.IsciTotalMasraf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IsciToplamUcret")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("IsciToplamUcret");
                });

            modelBuilder.Entity("TarlaOtomasyonProjesi2.Entities.Tarla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("BicimMasrafTotal")
                        .HasColumnType("REAL");

                    b.Property<double>("DigerIlacMasraf")
                        .HasColumnType("REAL");

                    b.Property<double>("DigerNasraflar")
                        .HasColumnType("REAL");

                    b.Property<double>("Donum")
                        .HasColumnType("REAL");

                    b.Property<double>("EkipmanMaliyet")
                        .HasColumnType("REAL");

                    b.Property<double>("GubreKg")
                        .HasColumnType("REAL");

                    b.Property<double>("GubreKgBirimFiyat")
                        .HasColumnType("REAL");

                    b.Property<double>("HolderlemeMasraf")
                        .HasColumnType("REAL");

                    b.Property<double>("IlacEkim1Masraf")
                        .HasColumnType("REAL");

                    b.Property<double>("IlacEkim2masraf")
                        .HasColumnType("REAL");

                    b.Property<double>("Maliyet")
                        .HasColumnType("REAL");

                    b.Property<double>("MatozLitre")
                        .HasColumnType("REAL");

                    b.Property<double>("MatozLitreBirimFiyat")
                        .HasColumnType("REAL");

                    b.Property<string>("TarlaParselNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TohumKg")
                        .HasColumnType("REAL");

                    b.Property<double>("TohumKgBirimFiyat")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Tarlalar");
                });
#pragma warning restore 612, 618
        }
    }
}
